### ISSUE TITLE
cannot import name SEASON_TYPE_TO_IDX error

### ISSUE THREAD

**Issue by knasil** [lgfrbcsgo/wot-customization-manager#6]
Hi, thanks for your great contribution!
I am having trouble executing customizationmanager.pyc. It gives the following error message in python.log (worldoftanks 1.6.0.0 (compiled at 12:03:51 Jul 30 2019) starting on Wed Aug  7 15:14:30 2019):

==============================================================
2019-08-07 15:14:54.941: INFO: [SL_PRO] Skipped Script: mod_customizationmanager.pyc
2019-08-07 15:14:54.941: INFO: 
2019-08-07 15:14:54.942: ERROR: [EXCEPTION] (<string>, 611):
Traceback (most recent call last):
  File "<string>", line 599, in _findValidMODs
  File "scripts/common/Lib/importlib/__init__.py", line 37, in import_module
  File "./scripts/client/gui/mods/mod_customizationmanager.py", line 18, in <module>
ImportError: cannot import name SEASON_TYPE_TO_IDX

==============================================================
Is this a common problem or am I doing something wrong? Thanks

**Comment by knasil** [comment]
hi, somehow it  was sorted in the next iteration of Aslain mod. It was probably something to do with the modpack. Cheers and thanks for the work!
